[package]
edition = "2021"
name = "x86_demo"
version = "0.1.0"

[dependencies]
bitflags = "1.3"
bootloader = "0.9.23"
lazy_static = {version = "1.4", features = ["spin_no_std"]}
log = "0.4"
uart_16550 = "0.2"
x86_64 = "0.14.2"
